source 'http://rubygems.org'

gem 'sinatra',  '~> 1.4.2'
gem 'thin',     '~> 1.5.1'
gem 'heroku',   '~> 2.39.3'
gem 'json',     '~> 1.7.7'
gem 'pony',     '~> 1.4.1'
gem 'debugger', '~> 1.6.0'
gem 'rerun'
gem 'shotgun',  '~> 0.9'